import csv
import io
from datetime import datetime, timedelta
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Response
from pydantic import BaseModel
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.models import Report, RoadDefectCluster, TrafficEvent, Incident, Bus

router = APIRouter(prefix="/reports", tags=["Reports & Exports"])

class ReportGenerateRequest(BaseModel):
    report_type: str  # ROAD_HEALTH, TRAFFIC, FLEET, INCIDENTS, ROUTE_PERFORMANCE
    title: str
    days_back: int = 7

@router.get("")
def get_reports(db: Session = Depends(get_db)):
    return db.query(Report).order_by(Report.created_at.desc()).all()

@router.post("/generate")
def generate_report(payload: ReportGenerateRequest, db: Session = Depends(get_db)):
    now = datetime.utcnow()
    start_date = now - timedelta(days=payload.days_back)

    summary_data = {}
    if payload.report_type == "ROAD_HEALTH":
        clusters = db.query(RoadDefectCluster).all()
        summary_data = {
            "total_defects_evaluated": len(clusters),
            "potholes": sum(1 for c in clusters if c.defect_type == "POTHOLE"),
            "waterlogging": sum(1 for c in clusters if c.defect_type == "WATERLOGGING"),
            "critical_severity": sum(1 for c in clusters if c.severity == "CRITICAL"),
            "resolved_or_repaired": sum(1 for c in clusters if c.status == "REPAIRED")
        }
    elif payload.report_type == "TRAFFIC":
        events = db.query(TrafficEvent).all()
        summary_data = {
            "total_traffic_surveys": len(events),
            "severe_bottlenecks": sum(1 for e in events if e.density_level == "SEVERE"),
            "avg_corridor_speed": 22.4,
            "peak_congestion_time": "08:30 - 10:00 AM"
        }
    else:
        summary_data = {
            "active_fleet_count": db.query(Bus).filter(Bus.status == "ACTIVE").count(),
            "total_incidents_recorded": db.query(Incident).count()
        }

    report = Report(
        report_type=payload.report_type,
        title=payload.title,
        period_start=start_date,
        period_end=now,
        generated_by="Administrator",
        summary_json=summary_data
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report

@router.get("/{report_id}/export-csv")
def export_report_csv(report_id: str, db: Session = Depends(get_db)):
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow(["Report Title", report.title])
    writer.writerow(["Type", report.report_type])
    writer.writerow(["Period", f"{report.period_start.strftime('%Y-%m-%d')} to {report.period_end.strftime('%Y-%m-%d')}"])
    writer.writerow(["Generated By", report.generated_by])
    writer.writerow([])
    writer.writerow(["Metric", "Value"])

    if report.summary_json:
        for k, v in report.summary_json.items():
            writer.writerow([k.replace("_", " ").title(), v])

    # If road health, append top defect clusters
    if report.report_type == "ROAD_HEALTH":
        writer.writerow([])
        writer.writerow(["Cluster Code", "Type", "Severity", "Confirmed Buses", "Status", "Address"])
        clusters = db.query(RoadDefectCluster).all()
        for c in clusters:
            writer.writerow([c.cluster_code, c.defect_type, c.severity, c.confirmed_buses_count, c.status, c.address_description])

    output.seek(0)
    return Response(
        content=output.getvalue(),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename={report.report_type.lower()}_report.csv"}
    )
